apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service-blue

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment-service
      version: blue

  template:
    metadata:
      labels:
        app: payment-service
        version: blue

    spec:
      containers:
        - name: payment-service
          image: chaitanyakommi/payment:4b58543772dd42a5af16b2284e80fbe221ace10a
          ports:
            - containerPort: 5002