apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service-green

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment-service
      version: green

  template:
    metadata:
      labels:
        app: payment-service
        version: green

    spec:
      containers:
        - name: payment-service
          image: chaitanyakommi/payment:fc80e4ec858769e174708f2233c13639e0c61cc9
          ports:
            - containerPort: 5002