apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service-blue

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment-service
      version: blue

  template:
    metadata:
      labels:
        app: payment-service
        version: blue

    spec:
      containers:
        - name: payment-service
          image: chaitanyakommi/payment-service:7492bcb4abd889cea96dcf682dcf9afbe37f79b5
          ports:
            - containerPort: 5002