apiVersion: apps/v1
kind: Deployment

metadata:
  name: cart-service-blue

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cart-service
      version: blue

  template:
    metadata:
      labels:
        app: cart-service
        version: blue

    spec:
      containers:
        - name: cart-service
          image: chaitanyakommi/cart:4b58543772dd42a5af16b2284e80fbe221ace10a
          ports:
            - containerPort: 5001