apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-service-green

spec:
  replicas: 2

  selector:
    matchLabels:
      app: catalog-service
      version: green

  template:
    metadata:
      labels:
        app: catalog-service
        version: green

    spec:
      containers:
        - name: catalog-service
          image: chaitanyakommi/catalog-service:7492bcb4abd889cea96dcf682dcf9afbe37f79b5
          ports:
            - containerPort: 5050