apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-service-green

spec:
  replicas: 2

  selector:
    matchLabels:
      app: catalog-service
      version: green

  template:
    metadata:
      labels:
        app: catalog-service
        version: green

    spec:
      containers:
        - name: catalog-service
          image: chaitanyakommi/catalog:fc80e4ec858769e174708f2233c13639e0c61cc9
          ports:
            - containerPort: 5050